name: easy_future_builder
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  strict: ^2.1.0
